### ISSUE TITLE
Implement Global Variables

### ISSUE THREAD

**Issue by d-ellis** [d-ellis/dynamicprompts#1]
Currently [dynamicprompts](https://github.com/adieyal/dynamicprompts) will support variables being passed into lower contexts, but it doesn't support the same in reverse. So given the following wildcard definition:
```yaml
example:
  - ${inner=innerExample} Outer variable is ${outer} & Inner variable is ${inner}
```
And this prompt
```
${outer=outerExample} __example__
```
It will resolve to `Outer variable is outerExample & Inner variable is innerExample`.

However if we add a variable access to the main prompt, like so:
```
${outer=outerExample} __example__ ${inner}
```
Then it will throw an error because the `inner` variable isn't defined in the top context.

It would be good if the variables could be set up with a global scope, as then you could have a wildcard that defines a subject and some related colors, as well as a wildcard to define a setting, which could use those color definitions. Something like so:
```yaml
image:
  subject:
    - grape ${color=purple}
    - banana ${color=yellow}
    - lime ${color=green}
  setting:
    - shirt
    - background
    - canvas
```
And this could be used with a prompt like:
```
A __image/subject__ on a ${color} __image/setting__
```
